// Pane content for the <Terminal> slides. It lives here rather than in slide
// frontmatter because the sample output contains quotes and backslashes, which
// cannot survive a Vue attribute.

const cra = [
  'PS C:\\dev> npx create-react-app AwesomeApp26',
  '',
  'Creating a new React app in C:\\dev\\AwesomeApp26.',
  '',
  'Installing packages. This might take a couple of minutes.',
  'Installing react, react-dom, and react-scripts with cra-template...',
  '',
  'added 1487 packages in 2m',
  '',
  '243 packages are looking for funding',
  '  run `npm fund` for details',
  '',
  'Initialized a git repository.',
  'Success! Created AwesomeApp26 at C:\\dev\\AwesomeApp26',
  '',
  'We suggest that you begin by typing:',
  '',
  '  cd AwesomeApp26',
  '  npm start',
  '',
  'Happy hacking!',
]

const nodemon = [
  'PS C:\\dev\\AwesomeApp26\\api> nodemon server.js',
  '',
  '[nodemon] 3.1.0',
  '[nodemon] to restart at any time, enter `rs`',
  '[nodemon] watching path(s): *.*',
  '[nodemon] watching extensions: js,mjs,cjs,json',
  '[nodemon] starting `node server.js`',
  '',
  'api listening on http://localhost:4000',
  'db pool ready (max 10)',
  '',
  '[nodemon] restarting due to changes...',
  '[nodemon] starting `node server.js`',
  'api listening on http://localhost:4000',
]

const vite = [
  'PS C:\\dev\\AwesomeApp26> bun run vite',
  '',
  '  VITE v7.1.4  ready in 312 ms',
  '',
  '  ➜  Local:   http://localhost:5173/',
  '  ➜  Network: http://192.168.1.24:5173/',
  '  ➜  press h + enter to show help',
  '',
  '9:41:02 AM [vite] hmr update /src/cart/Cart.tsx',
  '9:41:14 AM [vite] hmr update /src/cart/totals.ts',
  '9:41:14 AM [vite] hmr update /src/cart/Cart.tsx',
  '9:42:03 AM [vite] page reload src/main.tsx',
]

const git = [
  'PS C:\\dev\\AwesomeApp26> git status',
  'On branch feat/checkout',
  'Your branch is up to date with origin/feat/checkout.',
  '',
  'Changes not staged for commit:',
  '        modified:   src/cart/Cart.tsx',
  '        modified:   src/cart/useCart.ts',
  '',
  'PS C:\\dev\\AwesomeApp26> git add -A',
  'PS C:\\dev\\AwesomeApp26> git commit -m "split cart totals out of the view"',
  '[feat/checkout 9f2a1c4] split cart totals out of the view',
  ' 2 files changed, 41 insertions(+), 18 deletions(-)',
  '',
  'PS C:\\dev\\AwesomeApp26> git fetch origin',
  'remote: Enumerating objects: 34, done.',
  'From github.com:itenium-be/AwesomeApp26',
  '   1ab90ff..7c3e820  main -> origin/main',
  '',
  'PS C:\\dev\\AwesomeApp26> git rebase origin/main',
  'Successfully rebased and updated refs/heads/feat/checkout.',
]

const claude = [
  'PS C:\\dev\\AwesomeApp26> claude',
  '',
  '  ▐▛███▜▌   Claude Code v2.1.0',
  '  ▝▜█████▛▘ C:\\dev\\AwesomeApp26',
  '',
  '> extract the totals calculation out of Cart.tsx',
  '',
  '● Read(src/cart/Cart.tsx)',
  '  ⎿ Read 214 lines',
  '',
  '● Write(src/cart/totals.ts)',
  '  ⎿ Wrote 38 lines',
  '',
  '● Update(src/cart/Cart.tsx)',
  '  ⎿ Updated with 6 additions and 47 removals',
  '',
  '● Bash(bun test cart)',
  '  ⎿ 12 pass, 0 fail',
  '',
  '  Done. Cart.tsx is 41 lines shorter.',
  '',
  '>',
]

const claudeLeft = [
  'PS C:\\dev\\AwesomeApp26> claude',
  '',
  '  \u2590\u259b\u2588\u2588\u2588\u259c\u258c   Claude Code v2.1.0',
  '  \u259d\u259c\u2588\u2588\u2588\u2588\u2588\u259b\u2598 C:\\dev\\AwesomeApp26',
  '',
  '> add a discount code field to the checkout form',
  '',
  '\u25cf Read(src/checkout/CheckoutForm.tsx)',
  '  \u237f Read 186 lines',
  '',
  '\u25cf Write(src/checkout/DiscountField.tsx)',
  '  \u237f Wrote 52 lines',
  '',
  '\u25cf Update(src/checkout/CheckoutForm.tsx)',
  '  \u237f Updated with 11 additions',
  '',
  '\u25cf Bash(bun test checkout)',
  '  \u237f 8 pass, 0 fail',
  '',
  '> now wire it to the pricing endpoint',
  '',
  '\u25cf Read(src/api/pricing.ts)',
]

const claudeRight = [
  'wouter@dev:~/AwesomeApp26$ claude',
  '',
  '  \u2590\u259b\u2588\u2588\u2588\u259c\u258c   Claude Code v2.1.0',
  '  \u259d\u259c\u2588\u2588\u2588\u2588\u2588\u259b\u2598 ~/AwesomeApp26',
  '',
  '> migrate the cart reducer to zustand',
  '',
  '\u25cf Read(src/cart/useCart.ts)',
  '  \u237f Read 203 lines',
  '',
  '\u25cf Write(src/cart/store.ts)',
  '  \u237f Wrote 74 lines',
  '',
  '\u25cf Update(src/cart/Cart.tsx)',
  '  \u237f Updated with 9 additions and 31 removals',
  '',
  '\u25cf Bash(bun test)',
  '  \u237f 31 pass, 4 fail',
  '',
  '  4 failures in checkout/*. Investigating.',
  '',
  '\u25cf Read(src/checkout/CheckoutForm.tsx)',
]

const pwsh = (at, panes) => ({ title: 'AwesomeApp26 - PowerShell', icon: 'powershell', at, panes })

// Three panes, named one click at a time. No agent yet.
export const beforeAI = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'cra', label: 'create-react-app', at: 1, lines: cra },
          { id: 'nodemon', label: 'nodemon', at: 2, lines: nodemon },
        ],
      },
      { id: 'git', label: 'git commands etc', at: 3, lines: git },
    ],
  }),
]

// Same window, one pane handed over.
export const handover = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'vite', label: 'bun run vite', at: 1, lines: vite },
          { id: 'git2', label: 'git commands etc', at: 2, lines: git },
        ],
      },
      { id: 'claude', label: 'claude code', at: 3, lines: claude },
    ],
  }),
]

// One click swaps the whole window for a second tab running two agents.
export const takeover = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'vite3', label: 'bun run vite', at: 0, lines: vite },
          { id: 'nodemon3', label: 'nodemon', at: 0, lines: nodemon },
        ],
      },
      { id: 'git3', label: 'git commands etc', at: 0, lines: git },
    ],
  }),
  {
    title: 'Ubuntu',
    icon: 'ubuntu',
    at: 1,
    panes: {
      split: 'vertical',
      children: [
        { id: 'claudeL', label: 'claude code', at: 2, lines: claudeLeft },
        { id: 'claudeR', label: 'claude code', at: 3, lines: claudeRight },
      ],
    },
  },
]

export const agentSessions = [
  [
    'wouter@dev:~/wt/discount-code$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/discount-code',
    '',
    '> add a discount code field to the checkout form',
    '',
    '● Read(src/checkout/CheckoutForm.tsx)',
    '  ⍿ Read 186 lines',
    '',
    '● Write(src/checkout/DiscountField.tsx)',
    '  ⍿ Wrote 52 lines',
    '',
    '● Bash(bun test checkout)',
    '  ⍿ 8 pass, 0 fail',
    '',
  ],
  [
    'wouter@dev:~/wt/cart-zustand$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/cart-zustand',
    '',
    '> migrate the cart reducer to zustand',
    '',
    '● Read(src/cart/useCart.ts)',
    '  ⍿ Read 203 lines',
    '',
    '● Write(src/cart/store.ts)',
    '  ⍿ Wrote 74 lines',
    '',
    '● Bash(bun test)',
    '  ⍿ 31 pass, 4 fail',
    '',
  ],
  [
    'wouter@dev:~/wt/perf-checkout$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/perf-checkout',
    '',
    '> the checkout page is 4s to interactive, fix it',
    '',
    '● Bash(bun run build --analyze)',
    '  ⍿ main chunk 1.2 MB',
    '',
    '● Update(src/routes/checkout.tsx)',
    '  ⍿ lazy import added',
    '',
    '● Bash(bun run build)',
    '  ⍿ main chunk 410 kB',
    '',
  ],
  [
    'wouter@dev:~/wt/optimistic-cart$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/optimistic-cart',
    '',
    '> add optimistic updates to the cart mutations',
    '',
    '● Read(src/cart/mutations.ts)',
    '  ⍿ Read 94 lines',
    '',
    '● Update(src/cart/mutations.ts)',
    '  ⍿ 3 additions, 1 removal',
    '',
    '● Bash(bun test cart)',
    '  ⍿ 12 pass, 2 fail',
    '',
  ],
  [
    'wouter@dev:~/wt/flaky-order$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/flaky-order',
    '',
    '> the flaky order-confirmation test, make it deterministic',
    '',
    '● Bash(bun test order --repeat 20)',
    '  ⍿ 17 pass, 3 fail',
    '',
    '● Read(test/order.spec.ts)',
    '  ⍿ Read 141 lines',
    '',
    '● Update(test/order.spec.ts)',
    '  ⍿ fake timers',
    '',
  ],
  [
    'wouter@dev:~/wt/react-19$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/react-19',
    '',
    '> bump to react 19 and fix whatever breaks',
    '',
    '● Bash(bun add react@19 react-dom@19)',
    '  ⍿ installed 2 packages',
    '',
    '● Bash(bun run build)',
    '  ⍿ 14 type errors',
    '',
    '● Update(src/main.tsx)',
    '  ⍿ createRoot signature',
    '',
  ],
]

export const graves = [
  {
    sigil: '🎃',
    title: 'Two Claudes, Same Files',
    lines: ['Half implemented features'],
    at: 1,
  },
  {
    sigil: '👻',
    title: 'Unstable Bun Serve',
    lines: ['Constant compilation errors'],
    at: 2,
  },
  {
    sigil: '🦇',
    title: 'Unstable test runs',
    lines: ['Tests fail because of that other Claude'],
    at: 3,
  },
  {
    sigil: '💀',
    title: 'Two confused Claudes',
    lines: [
      'git checkout kills the other Claude\'s work',
      'git commit includes unrelated work',
    ],
    at: 4,
  },
]
