// Pane content for the <Terminal> slides. It lives here rather than in slide
// frontmatter because the sample output contains quotes and backslashes, which
// cannot survive a Vue attribute.

const cra = [
  'PS C:\\dev> npx create-react-app AwesomeApp26',
  '',
  'Creating a new React app in C:\\dev\\AwesomeApp26.',
  '',
  'Installing packages. This might take a couple of minutes.',
  'Installing react, react-dom, and react-scripts with cra-template...',
  '',
  'added 1487 packages in 2m',
  '',
  '243 packages are looking for funding',
  '  run `npm fund` for details',
  '',
  'Initialized a git repository.',
  'Success! Created AwesomeApp26 at C:\\dev\\AwesomeApp26',
  '',
  'We suggest that you begin by typing:',
  '',
  '  cd AwesomeApp26',
  '  npm start',
  '',
  'Happy hacking!',
]

const nodemon = [
  'PS C:\\dev\\AwesomeApp26\\api> nodemon server.js',
  '',
  '[nodemon] 3.1.0',
  '[nodemon] to restart at any time, enter `rs`',
  '[nodemon] watching path(s): *.*',
  '[nodemon] watching extensions: js,mjs,cjs,json',
  '[nodemon] starting `node server.js`',
  '',
  'api listening on http://localhost:4000',
  'db pool ready (max 10)',
  '',
  '[nodemon] restarting due to changes...',
  '[nodemon] starting `node server.js`',
  'api listening on http://localhost:4000',
]

const vite = [
  'PS C:\\dev\\AwesomeApp26> bun run vite',
  '',
  '  VITE v7.1.4  ready in 312 ms',
  '',
  '  ➜  Local:   http://localhost:5173/',
  '  ➜  Network: http://192.168.1.24:5173/',
  '  ➜  press h + enter to show help',
  '',
  '9:41:02 AM [vite] hmr update /src/cart/Cart.tsx',
  '9:41:14 AM [vite] hmr update /src/cart/totals.ts',
  '9:41:14 AM [vite] hmr update /src/cart/Cart.tsx',
  '9:42:03 AM [vite] page reload src/main.tsx',
]

const git = [
  'PS C:\\dev\\AwesomeApp26> git status',
  'On branch feat/checkout',
  'Your branch is up to date with origin/feat/checkout.',
  '',
  'Changes not staged for commit:',
  '        modified:   src/cart/Cart.tsx',
  '        modified:   src/cart/useCart.ts',
  '',
  'PS C:\\dev\\AwesomeApp26> git add -A',
  'PS C:\\dev\\AwesomeApp26> git commit -m "split cart totals out of the view"',
  '[feat/checkout 9f2a1c4] split cart totals out of the view',
  ' 2 files changed, 41 insertions(+), 18 deletions(-)',
  '',
  'PS C:\\dev\\AwesomeApp26> git fetch origin',
  'remote: Enumerating objects: 34, done.',
  'From github.com:itenium-be/AwesomeApp26',
  '   1ab90ff..7c3e820  main -> origin/main',
  '',
  'PS C:\\dev\\AwesomeApp26> git rebase origin/main',
  'Successfully rebased and updated refs/heads/feat/checkout.',
]

const claude = [
  'PS C:\\dev\\AwesomeApp26> claude',
  '',
  '  ▐▛███▜▌   Claude Code v2.1.0',
  '  ▝▜█████▛▘ C:\\dev\\AwesomeApp26',
  '',
  '> extract the totals calculation out of Cart.tsx',
  '',
  '● Read(src/cart/Cart.tsx)',
  '  ⎿ Read 214 lines',
  '',
  '● Write(src/cart/totals.ts)',
  '  ⎿ Wrote 38 lines',
  '',
  '● Update(src/cart/Cart.tsx)',
  '  ⎿ Updated with 6 additions and 47 removals',
  '',
  '● Bash(bun test cart)',
  '  ⎿ 12 pass, 0 fail',
  '',
  '  Done. Cart.tsx is 41 lines shorter.',
  '',
  '>',
]

const claudeLeft = [
  'PS C:\\dev\\AwesomeApp26> claude',
  '',
  '  \u2590\u259b\u2588\u2588\u2588\u259c\u258c   Claude Code v2.1.0',
  '  \u259d\u259c\u2588\u2588\u2588\u2588\u2588\u259b\u2598 C:\\dev\\AwesomeApp26',
  '',
  '> add a discount code field to the checkout form',
  '',
  '\u25cf Read(src/checkout/CheckoutForm.tsx)',
  '  \u237f Read 186 lines',
  '',
  '\u25cf Write(src/checkout/DiscountField.tsx)',
  '  \u237f Wrote 52 lines',
  '',
  '\u25cf Update(src/checkout/CheckoutForm.tsx)',
  '  \u237f Updated with 11 additions',
  '',
  '\u25cf Bash(bun test checkout)',
  '  \u237f 8 pass, 0 fail',
  '',
  '> now wire it to the pricing endpoint',
  '',
  '\u25cf Read(src/api/pricing.ts)',
]

const claudeRight = [
  'wouter@dev:~/AwesomeApp26$ claude',
  '',
  '  \u2590\u259b\u2588\u2588\u2588\u259c\u258c   Claude Code v2.1.0',
  '  \u259d\u259c\u2588\u2588\u2588\u2588\u2588\u259b\u2598 ~/AwesomeApp26',
  '',
  '> migrate the cart reducer to zustand',
  '',
  '\u25cf Read(src/cart/useCart.ts)',
  '  \u237f Read 203 lines',
  '',
  '\u25cf Write(src/cart/store.ts)',
  '  \u237f Wrote 74 lines',
  '',
  '\u25cf Update(src/cart/Cart.tsx)',
  '  \u237f Updated with 9 additions and 31 removals',
  '',
  '\u25cf Bash(bun test)',
  '  \u237f 31 pass, 4 fail',
  '',
  '  4 failures in checkout/*. Investigating.',
  '',
  '\u25cf Read(src/checkout/CheckoutForm.tsx)',
]

const pwsh = (at, panes) => ({ title: 'AwesomeApp26 - PowerShell', icon: 'powershell', at, panes })

// Three panes, named one click at a time. No agent yet.
export const beforeAI = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'cra', label: 'create-react-app', at: 1, lines: cra },
          { id: 'nodemon', label: 'nodemon', at: 2, lines: nodemon },
        ],
      },
      { id: 'git', label: 'git commands etc', at: 3, lines: git },
    ],
  }),
]

// Same window, one pane handed over.
export const handover = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'vite', label: 'bun run vite', at: 1, lines: vite },
          { id: 'git2', label: 'git commands etc', at: 2, lines: git },
        ],
      },
      { id: 'claude', label: 'claude code', at: 3, lines: claude },
    ],
  }),
]

// One click swaps the whole window for a second tab running two agents.
export const takeover = [
  pwsh(0, {
    split: 'vertical',
    children: [
      {
        split: 'horizontal',
        children: [
          { id: 'vite3', label: 'bun run vite', at: 0, lines: vite },
          { id: 'nodemon3', label: 'nodemon', at: 0, lines: nodemon },
        ],
      },
      { id: 'git3', label: 'git commands etc', at: 0, lines: git },
    ],
  }),
  {
    title: 'Ubuntu',
    icon: 'ubuntu',
    at: 1,
    panes: {
      split: 'vertical',
      children: [
        { id: 'claudeL', label: 'claude code', at: 2, lines: claudeLeft },
        { id: 'claudeR', label: 'claude code', at: 3, lines: claudeRight },
      ],
    },
  },
]

// 28 lines each: the pane is exactly that tall, so the click can scroll it to its second half.
export const agentSessions = [
  [
    'wouter@dev:~/wt/discount-code$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/discount-code',
    '',
    '> add a discount code field to the checkout form',
    '',
    '● Read(src/checkout/CheckoutForm.tsx)',
    '  ⍿ Read 186 lines',
    '',
    '● Write(src/checkout/DiscountField.tsx)',
    '  ⍿ Wrote 52 lines',
    '',
    '● Bash(bun test checkout)',
    '  ⍿ 8 pass, 0 fail',
    '',
    '> now wire it to the pricing endpoint',
    '',
    '● Read(src/api/pricing.ts)',
    '  ⍿ Read 88 lines',
    '',
    '● Update(src/checkout/DiscountField.tsx)',
    '  ⍿ Updated with 14 additions',
    '',
    '● Bash(bun test checkout)',
    '  ⍿ 11 pass, 0 fail',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/cart-zustand$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/cart-zustand',
    '',
    '> migrate the cart reducer to zustand',
    '',
    '● Read(src/cart/useCart.ts)',
    '  ⍿ Read 203 lines',
    '',
    '● Write(src/cart/store.ts)',
    '  ⍿ Wrote 74 lines',
    '',
    '● Bash(bun test)',
    '  ⍿ 31 pass, 4 fail',
    '',
    '  4 failures in checkout/*. Investigating.',
    '',
    '● Read(src/checkout/CheckoutForm.tsx)',
    '  ⍿ Read 186 lines',
    '',
    '● Update(src/cart/store.ts)',
    '  ⍿ Updated with 7 additions and 2 removals',
    '',
    '● Bash(bun test)',
    '  ⍿ 35 pass, 0 fail',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/perf-checkout$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/perf-checkout',
    '',
    '> the checkout page is 4s to interactive, fix it',
    '',
    '● Bash(bun run build --analyze)',
    '  ⍿ main chunk 1.2 MB',
    '',
    '● Update(src/routes/checkout.tsx)',
    '  ⍿ lazy import added',
    '',
    '● Bash(bun run build)',
    '  ⍿ main chunk 410 kB',
    '',
    '● Update(src/routes/checkout.tsx)',
    '  ⍿ Suspense fallback added',
    '',
    '● Bash(bun run lighthouse --url /checkout)',
    '  ⍿ TTI 1.3s (was 4.1s)',
    '',
    '● Bash(bun test routes)',
    '  ⍿ 19 pass, 0 fail',
    '',
    '  Done. 790 kB off the main chunk.',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/optimistic-cart$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/optimistic-cart',
    '',
    '> add optimistic updates to the cart mutations',
    '',
    '● Read(src/cart/mutations.ts)',
    '  ⍿ Read 94 lines',
    '',
    '● Update(src/cart/mutations.ts)',
    '  ⍿ 3 additions, 1 removal',
    '',
    '● Bash(bun test cart)',
    '  ⍿ 12 pass, 2 fail',
    '',
    '  The rollback path is untested. Adding it.',
    '',
    '● Update(test/cart.spec.ts)',
    '  ⍿ Wrote 2 cases',
    '',
    '● Update(src/cart/mutations.ts)',
    '  ⍿ 8 additions, 2 removals',
    '',
    '● Bash(bun test cart)',
    '  ⍿ 14 pass, 0 fail',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/flaky-order$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/flaky-order',
    '',
    '> the flaky order-confirmation test, make it deterministic',
    '',
    '● Bash(bun test order --repeat 20)',
    '  ⍿ 17 pass, 3 fail',
    '',
    '● Read(test/order.spec.ts)',
    '  ⍿ Read 141 lines',
    '',
    '● Update(test/order.spec.ts)',
    '  ⍿ fake timers',
    '',
    '● Bash(bun test order --repeat 20)',
    '  ⍿ 20 pass, 0 fail',
    '',
    '● Update(test/setup.ts)',
    '  ⍿ seeded Math.random',
    '',
    '● Bash(bun test --repeat 5)',
    '  ⍿ 96 pass, 0 fail',
    '',
    '  Done. No sleeps left in the suite.',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/react-19$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/react-19',
    '',
    '> bump to react 19 and fix whatever breaks',
    '',
    '● Bash(bun add react@19 react-dom@19)',
    '  ⍿ installed 2 packages',
    '',
    '● Bash(bun run build)',
    '  ⍿ 14 type errors',
    '',
    '● Update(src/main.tsx)',
    '  ⍿ createRoot signature',
    '',
    '● Update(src/cart/Cart.tsx)',
    '  ⍿ useRef initial value',
    '',
    '● Bash(bun run build)',
    '  ⍿ 0 errors, built in 3.4s',
    '',
    '● Bash(bun test)',
    '  ⍿ 128 pass, 0 fail',
    '',
    '  Done. 9 files touched.',
    '',
    '>',
  ],
  [
    'wouter@dev:~/wt/stripe-webhooks$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/stripe-webhooks',
    '',
    '> verify stripe webhook signatures before we replay them',
    '',
    '● Read(src/billing/webhook.ts)',
    '  ⍿ Read 118 lines',
    '',
    '● Update(src/billing/webhook.ts)',
    '  ⍿ 22 additions, 4 removals',
    '',
    '● Bash(bun test billing)',
    '  ⍿ 19 pass, 0 fail',
    '',
  ],
  [
    'wouter@dev:~/wt/a11y-checkout$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/a11y-checkout',
    '',
    '> the checkout form fails axe, fix the labels and focus order',
    '',
    '● Bash(bunx axe src/checkout)',
    '  ⍿ 11 violations',
    '',
    '● Update(src/checkout/CheckoutForm.tsx)',
    '  ⍿ 31 additions, 9 removals',
    '',
    '● Bash(bunx axe src/checkout)',
    '  ⍿ 0 violations',
    '',
  ],
  [
    'wouter@dev:~/wt/drop-moment$ claude',
    '',
    '  ▐▛███▜▌   Claude Code v2.1.0',
    '  ▝▜█████▛▘ ~/wt/drop-moment',
    '',
    '> rip moment.js out, date-fns everywhere',
    '',
    '● Bash(rg -l "from .moment." src)',
    '  ⍿ 23 files',
    '',
    '● Update(src/**/*.ts)',
    '  ⍿ 23 files changed',
    '',
    '● Bash(bun run build)',
    '  ⍿ main chunk -68 kB',
    '',
  ],
]

// The merge treadmill, one lap per click. Every branch here is local: main keeps
// moving because the agents in the other worktrees keep landing on it.
export const mergeRace = [
  { at: 0, text: 'wouter@dev:~/wt/checkout$ claude', tone: 'cmd' },
  { at: 0, text: '' },
  { at: 0, text: '> finish the checkout refactor and land it on main', tone: 'you' },
  { at: 0, text: '' },
  { at: 0, text: '\u25cf Bash(bun test)', tone: 'tool' },
  { at: 0, text: '  \u237f 128 pass, 0 fail', tone: 'dim' },
  { at: 0, text: '  Test run: 100% green. Ready to merge.', tone: 'ok' },
  { at: 1, text: '' },
  { at: 1, text: '\u25cf Bash(git merge main)', tone: 'tool' },
  { at: 1, text: '  \u237f CONFLICT (content): merge conflict in src/cart/Cart.tsx', tone: 'dim' },
  { at: 1, text: '  Oh noes! main has moved under me.', tone: 'bad' },
  { at: 2, text: '' },
  { at: 2, text: '\u25cf Bash(git rebase main)', tone: 'tool' },
  { at: 2, text: '  \u237f 2 conflicts resolved, successfully rebased', tone: 'dim' },
  { at: 2, text: '\u25cf Bash(bun run build && bun test)', tone: 'tool' },
  { at: 2, text: '  \u237f built in 3.4s \u00b7 131 pass, 0 fail', tone: 'dim' },
  { at: 2, text: '  Rebased. Rebuilt. Test run: 100% green.', tone: 'ok' },
  { at: 3, text: '' },
  { at: 3, text: '\u25cf Bash(git switch main && git merge --ff-only feat/checkout)', tone: 'tool' },
  { at: 3, text: '  \u237f fatal: Not possible to fast-forward, aborting.', tone: 'dim' },
  { at: 3, text: '  Main has moved under me again!', tone: 'bad' },
  { at: 4, text: '' },
  { at: 4, text: '\u25cf Bash(git rebase main && bun test)', tone: 'tool' },
  { at: 4, text: '  \u237f 4 conflicts resolved \u00b7 134 pass, 0 fail', tone: 'dim' },
  { at: 4, text: '  Test run: 100% green. Ready to merge.', tone: 'ok' },
  { at: 5, text: '' },
  { at: 5, text: '\u25cf Bash(git merge --ff-only feat/checkout)', tone: 'tool' },
  { at: 5, text: '  \u237f fatal: Not possible to fast-forward, aborting.', tone: 'dim' },
  { at: 5, text: '  main moved. Again. Rebasing.', tone: 'bad' },
  { at: 6, text: '' },
  { at: 6, text: '\u25cf Bash(git rebase main && bun test)', tone: 'tool' },
  { at: 6, text: '  \u237f 6 conflicts resolved \u00b7 137 pass, 0 fail', tone: 'dim' },
  { at: 6, text: "  I'm giving up. main moves faster than I can rebase onto it.", tone: 'bad' },
  { at: 6, text: '  Tell me when nobody else is landing and I will merge then.', tone: 'bad' },
  { at: 7, text: '' },
  { at: 7, text: '> okay you can merge now', tone: 'you' },
  { at: 7, text: '' },
  { at: 7, text: '\u25cf Bash(git merge --ff-only feat/checkout)', tone: 'tool' },
  { at: 7, text: '  \u237f Fast-forward. landed.', tone: 'ok' },
]

export const graves = [
  {
    sigil: '🎃',
    title: 'Working Tree',
    lines: ['Two agents, one file. Last write wins.'],
    at: 1,
  },
  {
    sigil: '💀',
    title: 'Git State',
    lines: ['Checkout moves.', 'Commit steals.', 'Stash vanishes.'],
    at: 2,
  },
  {
    sigil: '👻',
    title: 'Unstable\nDev Server',
    lines: ['It rebuilds & reloads all the time'],
    at: 3,
  },
  {
    sigil: '🦇',
    title: 'Unstable\nTest Run',
    lines: ['Red.', "From the other agent's in-progress work"],
    at: 4,
  },
]

// Slide 9 is the same four stones, already standing: one rights itself per click and
// its engraving dissolves into the cure. Derived from `graves` so the two slides can
// never drift apart.
const CURES = [
  { cureTitle: 'Working Tree', cureLines: ['Separate directories', '`.worktreeinclude` for `.env`'] },
  { cureTitle: 'Git State', cureLines: ['Shared `.git` folder', 'Since v2.5,<br>over a decade ago'] },
  { cureTitle: 'Dev Server', cureLines: ['Different ports', 'Hardlinked `node_modules` with pnpm or bun'] },
  { cureTitle: 'Test Run', cureLines: ['Own code only', 'Separate testcontainer'] },
]

export const risen = graves.map((g, i) => ({
  ...g,
  at: 0,
  cureAt: i + 1,
  cureSigil: '🕯️',
  ...CURES[i],
}))

export const series = [
  {
    sigil: '🏠',
    title: 'Homelab',
    subTitle: "I don't know networks, but Claude does!",
    at: 1,
    dimAt: 3,
    hideAt: 4,
  },
  {
    sigil: '🐧',
    title: 'Linux Migration',
    subTitle: 'How Claude made me abandon Windows',
    at: 2,
    dimAt: 3,
    hideAt: 4,
  },
  {
    sigil: '🏭',
    title: 'Dark Factory',
    subTitle: 'I wanted a merge queue,<br> I ended up with a dark factory',
    at: 3,
    expandAt: 4,
  },
]

// The three stages inside the expanded Dark Factory: what you must already have,
// what this talk is about, and where it lands.
export const seriesStages = [
  {
    at: 5,
    title: 'Guardrails & Backpressure',
    lines: ['lint & tsc dialed to 11'],
    groups: [{ label: 'Testing', lines: ['unit · component · e2e', 'architecture · mutation'] }],
  },
  {
    at: 6,
    title: 'Worktrees & Merge Queues',
    lines: ['one repo, n coding agents'],
    note: 'we are here',
  },
  {
    at: 7,
    title: 'Dark Factory',
    lines: ['lights out, nobody watching'],
  },
]
